spring:
  profiles:
    active: test
  application:
    name: ${APPLICATION_NAME}

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}

  jpa:
    show-sql: true
    database: ${DB_TYPE}
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true




  liquibase:
    change-log: db/changelog/main-changelog.yml
    enabled: true

server:
  servlet:
    context-path: /api
  port: 8080
