spring:
  profiles:
    active: dev
  application:
    name: ${APPLICATION_NAME}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}

  jpa:
    show-sql: true
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: db/changelog/main-changelog.yml
    enabled: true

server:
  servlet:
    context-path: /api
